# Create or update BIG-IP Forwarder; Base Declaration - Kafka

# Device 1

- name: Get BIG-IP Authentication Token from {{deviceName1}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{deviceName1}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip1_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

- name: Prepare the TS declaration
  template: src="{{ role_path }}/files/ts_kafka.json" dest="{{ role_path }}/files/{{ forwarderName }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ forwarderName }}; AS3 Build Simple HTTP Application
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ forwarderName }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: POST
    status_code: 200
    url: "https://{{deviceName1}}/mgmt/shared/telemetry/declare"
    validate_certs: no