# Create or update BIG-IP Forwarder; Base Declaration for Telemetry Streaming

# Device 1

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{bigip1Provider}}"
  delegate_to: localhost

- name: Get BIG-IP Authentication Token from {{bigip1Provider.server}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{bigip1Provider.user}}","password":"{{bigip1Provider.password}}","loginProviderName":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{bigip1Provider.server}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: "{{bigip1Provider.validate_certs}}"
  register: bigip1_auth_response
  retries: 30
  delay: 5
  until: "(bigip1_auth_response is successful) and (bigip1_auth_response.status == 200)"

- name: Assign Auth Token to Variable
  set_fact:
    bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

- name: Validate {{bigip1Provider.server}} TS Rest Worker is ready
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: GET
    url: "https://{{bigip1Provider.server}}/mgmt/shared/telemetry/available"
    validate_certs: "{{bigip1Provider.validate_certs}}"
  retries: 30
  delay: 5
  register: result
  until: "(result is successful) and (result.status == 200)"

- name: Prepare the TS declaration
  template: src="{{ role_path }}/templates/ts_declaration.j2" dest="{{ role_path }}/files/{{ forwarderName }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ forwarderName }}; AS3 Build Simple HTTP Application
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ forwarderName }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: POST
    status_code: 200
    url: "https://{{bigip1Provider.server}}/mgmt/shared/telemetry/declare"
    validate_certs: "{{bigip1Provider.validate_certs}}"