# Set up ElasticSearch index and types

- name: Wait for ElasticSearch to come up before configuring
  uri:
    url: "{{ elasticSearchBaseUrl }}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 5

- name: Check if ElasticSearch index {{ elasticSearchIndex }} exists
  uri:
    url: "{{ elasticSearchBaseUrl }}/{{ elasticSearchIndex }}"
    method: GET
    status_code:
      - 200
      - 404
  register: index_check

- debug:
    var: index_check
    verbosity: 2

- name: Create {{ elasticSearchIndex }} index if does not exist
  uri:
    url: "{{ elasticSearchBaseUrl }}/{{ elasticSearchIndex }}"
    method: PUT
    body: "{}"
    status_code: 200
    body_format: json
  when: index_check.status == 404

- name: Update {{ elasticSearchIndex }} index settings
  uri:
    url: "{{ elasticSearchBaseUrl }}/{{ elasticSearchIndex }}/_settings"
    method: PUT
    body: "{{ lookup('file','{{ role_path }}/files/index-settings.json') }}"
    status_code: 200
    body_format: json

- name: Update {{ elasticSearchIndex }} mappings settings
  uri:
    url: "{{ elasticSearchBaseUrl }}/{{ elasticSearchIndex }}/_mapping"
    method: PUT
    body: "{{ lookup('file','{{ role_path }}/files/mappings-settings.json') }}"
    status_code: 200
    body_format: json
