# Set up ElasticSearch index and types

- name: Wait for grafana to come up before configuring ElasticSearch
  uri:
    url: "{{ elasticSearchBaseUrl }}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 5

- name: Check if ElasticSearch index exists
  uri:
    url: "{{ elasticSearchBaseUrl }}/{{ elasticSearchIndex }}"
    method: GET
    status_code:
      - 200
      - 404
  register: index_check

- debug:
    var: index_check
    verbosity: 2

- name: Set ElasticSearch Index settings
  uri:
    url: "{{ elasticSearchBaseUrl }}/{{ elasticSearchIndex }}"
    method: PUT
    body: "{{ lookup('file','{{ role_path }}/files/index-settings.json') }}"
    status_code: 200
    body_format: json
  when: index_check.status == 404

- name: ElasticSearch Mappings settings
  uri:
    url: "{{ elasticSearchBaseUrl }}/{{ elasticSearchIndex }}/_mapping"
    method: PUT
    body: "{{ lookup('file','{{ role_path }}/files/mappings-settings.json') }}"
    status_code: 200
    body_format: json
