# Create or update BIG-IP Device; Clustered declaration

# Device 1

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{bigip1Provider}}"
  delegate_to: localhost

- name: Get BIG-IP Authentication Token from {{bigip1Provider.server}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{bigip1Provider.user}}","password":"{{bigip1Provider.password}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{bigip1Provider.server}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: "{{bigip1Provider.validate_certs}}"
  register: bigip1_auth_response
  retries: 30
  delay: 5
  until: "(bigip1_auth_response is successful) and (bigip1_auth_response.status == 200)"

- name: Assign Auth Token to Variable
  set_fact:
    bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

- name: Validate {{bigip1Provider.server}} DO Rest Worker is ready
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: GET
    url: "https://{{bigip1Provider.server}}/mgmt/shared/declarative-onboarding/available"
    validate_certs: "{{bigip1Provider.validate_certs}}"
  retries: 30
  delay: 5
  register: result
  until: "(result is successful) and (result.status == 200)"

- name: Prepare the DO declaration 1
  template: src="{{ role_path }}/files/do_cluster_bigip1.json" dest="{{ role_path }}/files/{{ bigip1Provider.server }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ bigip1Provider.server }}; Clustered declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ bigip1Provider.server }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: POST
    status_code: 202
    url: "https://{{bigip1Provider.server}}/mgmt/shared/declarative-onboarding"
    validate_certs: "{{bigip1Provider.validate_certs}}"

- name: Wait for Sync to happen or race condition will occur
  pause:
    seconds: 30

# Device 2

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{bigip2Provider}}"
  delegate_to: localhost

- name: Get BIG-IP Authentication Token from {{bigip2Provider.server}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{bigip2Provider.user}}","password":"{{bigip2Provider.password}}","loginProviderName":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{bigip2Provider.server}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: "{{bigip2Provider.validate_certs}}"
  register: bigip2_auth_response
  retries: 30
  delay: 5
  until: "(bigip2_auth_response is successful) and (bigip2_auth_response.status == 200)"

- name: Assign Auth Token to Variable
  set_fact:
    bigip2_auth_token: "{{ bigip2_auth_response.json.token.token }}"

- name: Validate {{bigip2Provider.server}} DO Rest Worker is ready
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip2_auth_token }}"
    method: GET
    url: "https://{{bigip2Provider.server}}/mgmt/shared/declarative-onboarding/available"
    validate_certs: "{{bigip2Provider.validate_certs}}"
  retries: 30
  delay: 5
  register: result
  until: "(result is successful) and (result.status == 200)"

- name: Prepare the DO declaration 2
  template: src="{{ role_path }}/files/do_cluster_bigip2.json" dest="{{ role_path }}/files/{{ bigip2Provider.server }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ bigip2Provider.server }}; Clustered declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ bigip2Provider.server }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip2_auth_token }}"
    method: POST
    status_code: 202
    url: "https://{{bigip2Provider.server}}/mgmt/shared/declarative-onboarding"
    validate_certs: "{{bigip2Provider.validate_certs}}"