# Create or update BIG-IP Device; Clustered declaration

# Device 1

- name: Get BIG-IP Authentication Token from {{deviceName1}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{deviceName1}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip1_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

- name: Prepare the DO declaration 1
  template: src="{{ role_path }}/files/do_cluster_bigip1.json" dest="{{ role_path }}/files/{{ deviceName1 }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ deviceName1 }}; Clustered declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ deviceName1 }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: POST
    status_code: 202
    url: "https://{{deviceName1}}/mgmt/shared/declarative-onboarding"
    validate_certs: no

# Device 2

- name: Get BIG-IP Authentication Token from {{deviceName2}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{deviceName2}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip2_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigip2_auth_token: "{{ bigip2_auth_response.json.token.token }}"

- name: Prepare the DO declaration 2
  template: src="{{ role_path }}/files/do_cluster_bigip1.json" dest="{{ role_path }}/files/{{ deviceName2 }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ deviceName2 }}; Clustered declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ deviceName2 }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip2_auth_token }}"
    method: POST
    status_code: 202
    url: "https://{{deviceName2}}/mgmt/shared/declarative-onboarding"
    validate_certs: no